#!/bin/bash
#SBATCH --job-name=Preprocess_data
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --nodelist=compute-0-11
#SBATCH --partition=demo
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=28G
#SBATCH -o preprocess_train.out

# Inicializar conda
eval "$(/opt/miniconda3/bin/conda shell.bash hook)"
conda activate
conda activate transformers

nvidia-smi
echo $CUDA_VISIBLE_DEVICES

time python3 prepare_dataset.py
