#!/bin/bash
#SBATCH --job-name=Prot2Chem_Diff
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --nodelist=compute-0-12
#SBATCH --partition=demo
#SBATCH --gres=gpu:1
#SBATCH --mem-per-cpu=28G
#SBATCH -o train.out

# Inicializar conda
eval "$(/opt/miniconda3/bin/conda shell.bash hook)"
conda activate
conda activate transformers

nvidia-smi
echo $CUDA_VISIBLE_DEVICES

time python3 ../src/train_diffuser.py